version: '3.9'

services:
  eureka:
    build:
      context: ./eureka/eureka
    container_name: eureka
    ports:
      - "8761:8761"
    networks:
      - app-net

  gateway:
    build:
      context: ./gateway/gateway
    container_name: gateway
    depends_on:
      - eureka
    ports:
      - "8080:8080"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka:8761/eureka/
    networks:
      - app-net

  children-ms:
    build:
      context: ./children-ms/children-ms
    container_name: children-ms
    depends_on:
      - eureka
    ports:
      - "8082:8082"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka:8761/eureka/
      - DB_SERVER=${CHILDREN_DB_SERVER}
      - DB_PORT=${CHILDREN_DB_PORT}
      - DB_NAME=${CHILDREN_DB_NAME}
      - DB_USER=${CHILDREN_DB_USER}
      - DB_PASSWORD=${CHILDREN_DB_PASSWORD}
    networks:
      - app-net

  evaluations-ms:
    build:
      context: ./evaluations-ms/evaluations-ms
    container_name: evaluations-ms
    depends_on:
      - eureka
    ports:
      - "8083:8083"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka:8761/eureka/
      - DB_SERVER=${EVALUATIONS_DB_SERVER}
      - DB_PORT=${EVALUATIONS_DB_PORT}
      - DB_NAME=${EVALUATIONS_DB_NAME}
      - DB_USER=${EVALUATIONS_DB_USER}
      - DB_PASSWORD=${EVALUATIONS_DB_PASSWORD}
    networks:
      - app-net

networks:
  app-net:
    driver: bridge
