server:
  port: 8082
  error:
    include-message: always

spring:
  application:
    name: children-ms

  datasource:
    url: jdbc:postgresql://${DB_SERVER}:${DB_PORT}/${DB_NAME}?sslmode=require
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  flyway:
    enabled: true
    baseline-version: 1
    locations: classpath:db/migration
    sql-migration-suffixes: .sql
    baseline-on-migrate: true
    sql-migration-prefix: V
    schemas: public

  cloud:
    loadbalancer:
      ribbon:
        enabled: false

eureka:
  client:
    service-url:
      defaultZone: http://eureka:8761/eureka/
  instance:
    instance-id: ${spring.application.name}:${server.port}